image: docker:latest 

services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_NAME: "service-consumer"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_PATH: "jandrov/service-consumer"

before_script:
  - apk add --no-cache curl

build:
  stage: build  
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $DOCKER_REGISTRY/$DOCKER_PATH:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REGISTRY/$DOCKER_PATH:$CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_TAG

