version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  consumer:
    image: consumer:latest
    ports:
      - "9002:9002"
    environment:
      - PG_PASS=Pg.2025.appYk23_pg
      - PG_USER=app_pg
      - PG_DB=app_pg
      - PG_PORT=5432
      - PG_HOST=pg
      - PYTHONPATH=./
      - TOKEN=y25.app_pg.token$%
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  rabbitmq_data:
    driver: local

networks:
  app-network:
    driver: bridge
